# Generated by Django 5.1.7 on 2025-03-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='Descripción',
        ),
    ]
